### ISSUE TITLE
input map not set.

### ISSUE THREAD

**Issue by Cablefish1** [VP-GAMES/Godot4InventoryEditor#3]
![image](https://user-images.githubusercontent.com/37123600/218266161-6a54ccfa-6bc8-4ab3-99d6-c73bfa80e550.png)

Screenshot really says it all

**Comment by VP-GAMES** [comment]
![image](https://user-images.githubusercontent.com/74808066/218326717-1f0495c4-43b6-4f7f-9f09-3c4cab572994.png)
Every think looks good! Please update your Input map.
