### ISSUE TITLE
Godot 4.1 dev1 movement of example error

### ISSUE THREAD

**Issue by cyber-hub** [VP-GAMES/Godot4InventoryEditor#5]
In Godot 4.1 dev1 movement of player in 3D (res://addons/inventory_example/3d/Level1.tscn) don't works:

```
error: E 0:00:00:0482   Player.gd:14 @ handle_movement(): The InputMap action "move_up" doesn't exist. Did you mean "ui_up"?
```
same with the other move_*

Change to 'ui_up' etc. fixes it, except move_bottom needs ui_down,
in case somebody wonders.

Thank you for the plugin ;)

**Comment by VP-GAMES** [comment]
you have to create move_up, move_*... in your input map
